title: tExperience
description: >- # this means to ignore newlines until "baseurl:"
  Narayana Rengaswamy
twitter_username: rnarayana
github_username:  rnarayana
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: IN

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Narayana Rengaswamy"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Programmer, fantasy and sci-fi lover. In awe of life, earth and space. Fan of Sachin Tendulkar, Richard Feynman, J K Rowling, Abdul Kalam,..."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rnarayana"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rnarayana"
    - label: "GoodReads"
      icon: "fab fa-fw fa-goodreads"
      url: "https://www.goodreads.com/user/show/3333436-narayana"
    - label: "AM3"
      icon: "fa fa-fw fa-camera"
      url: "https://rnarayana.aminus3.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rnarayana"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rnarayana"
    - label: "GoodReads"
      icon: "fab fa-fw fa-goodreads"
      url: "https://www.goodreads.com/user/show/3333436-narayana"
    - label: "AM3"
      icon: "fa fa-fw fa-camera"
      url: "https://rnarayana.aminus3.com/"
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/